[package]
name = "git-mirror"
version = "0.1.0"
authors = ["m"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rayon = "1.4.0"